package org.jbpm.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Invoice implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 1)
    private java.util.List<org.jbpm.invoices.InvoiceLine> lines;

    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double total;

    @org.kie.api.definition.type.Position(value = 0)
    private org.jbpm.invoices.User user;

    public Invoice() {
    }
    
    public Invoice(org.jbpm.invoices.User user, java.util.List<org.jbpm.invoices.InvoiceLine> lines, java.lang.Double total) {
        this.user = user;
        this.lines = lines;
        this.total = total;
    }

    public java.util.List<org.jbpm.invoices.InvoiceLine> getLines() {
        return this.lines;
    }
    
    public void setLines(java.util.List<org.jbpm.invoices.InvoiceLine> lines) {
        this.lines = lines;
    }

    public java.lang.Double getTotal() {
        return this.total;
    }
    
    public void setTotal(java.lang.Double total) {
        this.total = total;
    }

    public org.jbpm.invoices.User getUser() {
        return this.user;
    }
    
    public void setUser(org.jbpm.invoices.User user) {
        this.user = user;
    }

}