package org.jbpm.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String login;

    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String password;

    public User() {
    }
    
    public User(java.lang.String login, java.lang.String password) {
        this.login = login;
        this.password = password;
    }

    public java.lang.String getLogin() {
        return this.login;
    }
    
    public void setLogin(java.lang.String login) {
        this.login = login;
    }

    public java.lang.String getPassword() {
        return this.password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }

}